from voiture import *
mycar1=()
mycar1 =voiture(marque="Toyota", modele="Corolla", puissancefiscale=5, couleur='rouge')
mycar1.affichage()

mycar2=voiture()
mycar2.affichage()
mycar3=voiture("fiat",2001,3,"blanc")
mycar3.affichage()
mycar4=voiture ( "","","","blanc")
mycar1.set_marque("Honda")
mycar1.set_couleur("vert")
mycar2.set_puissancefiscale(6)
print("attribues modifier")
mycar1.affichage()
mycar2.affichage()
print(mycar1)
mycar1.ajouter_option("GPS")
print("Options avant suppression:", mycar1.get_options())

print("verification de la presence de la GPS", mycar1.is_option_present("GPS"))
mycar1.supprimer_option("GPS")
print("verification de la presence de la GPS", mycar1.is_option_present("GPS"))
print(mycar1)